version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:current
    resource_class: medium

jobs:
  before:
    executor: base
    steps:
      - checkout
      - run:
          name: create files
          command: |
            mkdir foo
            # approx 12 GB
            for i in {1..120}
            do
              head -c 100MB /dev/urandom > "foo/random{$i}.txt"
            done
      - run: |
          ls -lh foo
      - persist_to_workspace:
          root: ~/project
          paths:
            - foo

  after:
    executor: base
    steps:
      - attach_workspace:
          at: ~/project
      - run: |
          ls -lh  ~/project

workflows:
  main:
    jobs:
      - before
      - after:
          requires:
            - before
