version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    resource_class: small
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install tree
      - run: |
          python3 -m venv venv
          # inspect
          tree -L 3 venv
      - run: |
          . venv/bin/activate
          pip install --upgrade pip
