version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:current
    resource_class: medium

jobs:
  before:
    executor: base
    steps:
      - checkout
      - run:
          name: compress foo/bar (zip)
          command: |
            cd foo
            # compression levels: -0 to -9 (defaults at -6)
            # -0: no compression, -9 being the highest and most CPU-intensive
            zip -9 -r bar.zip bar
      - persist_to_workspace:
          root: ~/project
          paths:
            - foo/bar.zip
      - persist_to_workspace:
          root: ~/project
          paths:
            - baz
  after:
    executor: base
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: unzip
          command: |
            cd foo
            unzip bar.zip
      - run: |
          ls -lh  ~/project/foo/bar
      - run: |
          ls -lh  ~/project/baz

workflows:
  main:
    jobs:
      - before
      - after:
          requires:
            - before
