version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:current
    resource_class: small

jobs:
  before:
    executor: base
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/project
          paths:
            - foo/bar
      - persist_to_workspace:
          root: ~/project
          paths:
            - baz
  after:
    executor: base
    steps:
      - attach_workspace:
          at: ~/project
      - run: |
          ls -lh  ~/project/foo/bar
      - run: |
          ls -lh  ~/project/baz

workflows:
  main:
    jobs:
      - before
      - after:
          requires:
            - before
