version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - run:
          name: generate some files
          command: |
            echo "lorem ipsum" > results.txt
      - persist_to_workspace:
          root: ~/project
          paths:
            - results.txt
  collect:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      # - run: echo "lorem ipsum" > results.txt
      - attach_workspace:
          at: ~/project

workflows:
  combine-files:
    jobs:
      - test:
          name: test1
      - test:
          name: test2
      - collect:
          requires:
            - test1
            - test2
            
