version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    resource_class: small
    steps:
      - run: |
          python3 -m venv venv
          ls -laH venv
          . venv/bin/activate
